server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mingrui:
  upload:
    path:
      windows: E:\\images
      linux: /shenyaqi/images
    img:
      host: http://image.mrshop.com